"""Write ODX/dummy_ecu.cdd: the Dummy ECU's diagnostics as a CANdela document, for TestExpert.

    python tools/make_dummy_cdd.py

It follows the structure CANdelaStudio writes - protocol services (REQ with CONSTCOMP and STATICCOMP), class
templates (DCLTMPL with SHSTATIC and DCLSRVTMPL), the variant's DIAGCLASS / DIAGINST / SERVICE, and state groups
with mayBeExec and trans - but it is generated here from the Dummy ECU's description, not exported by
CANdelaStudio.
"""
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from canexpert.simulator.ecu import EcuConfig  # noqa: E402
from canexpert.test_expert.dummy import dummy_description  # noqa: E402

TARGET = ROOT / "ODX" / "dummy_ecu.cdd"


class Writer:
    def __init__(self, description):
        self.d = description
        self.root = ElementTree.Element("CANDELA", dtdvers="9.0.102")
        self.doc = ElementTree.SubElement(self.root, "ECUDOC", manufacturer="CAN Expert", doctype="inst")
        comment = ElementTree.SubElement(self.doc, "DESC")
        ElementTree.SubElement(comment, "TUV").text = ("The Dummy ECU of CAN Expert, generated by tools/make_dummy_cdd.py "
                                                       "in CANdelaStudio's structure (not exported by CANdelaStudio).")
        ElementTree.SubElement(self.doc, "PROTOCOLSTANDARD").text = "UDS"
        self.datatypes = ElementTree.SubElement(self.doc, "DATATYPES")
        self.groups = ElementTree.SubElement(self.doc, "STATEGROUPS")
        self.protocols = ElementTree.SubElement(self.doc, "PROTOCOLSERVICES")
        self.templates = ElementTree.SubElement(self.doc, "DCLTMPLS")
        ecu = ElementTree.SubElement(self.doc, "ECU", id="ecu")
        self._named(ecu, "DummyECU", "Dummy ECU")
        self.variant = ElementTree.SubElement(ecu, "VAR", id="var_common")
        self._named(self.variant, "CommonDiagnostics", "Common diagnostics")
        self.ids = 0
        self.lengths = {}
        self.states = {}                 # ("session", id) / ("security", level or 0) -> 1-based index

    def _id(self, prefix):
        self.ids += 1
        return f"_{prefix}{self.ids:04d}"

    @staticmethod
    def _named(element, qual, name=None):
        name_element = ElementTree.SubElement(element, "NAME")
        ElementTree.SubElement(name_element, "TUV", {"xml:lang": "en-US"}).text = name or qual
        ElementTree.SubElement(element, "QUAL").text = qual
        return element

    def datatype(self, length):
        """A byte field of length bytes, for a DID's data."""
        if length not in self.lengths:
            element = ElementTree.SubElement(self.datatypes, "IDENT", id=self._id("dt"))
            self._named(element, f"Bytes{length}")
            ElementTree.SubElement(element, "CVALUETYPE", bl="8", bo="21", enc="uns", sz="no", qty="field",
                                   minsz=str(length), maxsz=str(length))
            ElementTree.SubElement(element, "PVALUETYPE", bl="8", bo="21", enc="uns", sz="no")
            self.lengths[length] = element.get("id")
        return self.lengths[length]

    def write_states(self):
        sessions = ElementTree.SubElement(self.groups, "STATEGROUP", id=self._id("sg"), spec="session")
        self._named(sessions, "Session")
        for session in sorted(self.d.sessions.values(), key=lambda s: s.id):
            self._named(ElementTree.SubElement(sessions, "STATE", id=self._id("st")), session.name.replace(" ", ""),
                        session.name)
            self.states[("session", session.id)] = len(self.states) + 1
        security = ElementTree.SubElement(self.groups, "STATEGROUP", id=self._id("sg"), spec="security")
        self._named(security, "SecurityAccess")
        self._named(ElementTree.SubElement(security, "STATE", id=self._id("st")), "Locked")
        self.states[("security", 0)] = len(self.states) + 1
        for level in sorted(self.d.security_levels):
            self._named(ElementTree.SubElement(security, "STATE", id=self._id("st")), f"UnlockedLevel{level}")
            self.states[("security", level)] = len(self.states) + 1

    def may_be_exec(self, access) -> str:
        sessions = access.sessions or set(self.d.sessions)
        levels = access.levels or {0, *self.d.security_levels}
        indexes = sorted([self.states[("session", s)] for s in sessions] + [self.states[("security", l)] for l in levels])
        return "(" + ",".join(str(index) for index in indexes) + ")"

    def protocol(self, qual, parts):
        """A PROTOCOLSERVICE: parts are ("const", value, bits), ("static", key, bits) or ("data",). Returns
        (its id, {key: STATICCOMP id})."""
        element = ElementTree.SubElement(self.protocols, "PROTOCOLSERVICE", id=self._id("ps"), func="1", phys="1")
        self._named(element, qual)
        request = ElementTree.SubElement(element, "REQ")
        statics = {}
        for part in parts:
            if part[0] == "const":
                self._named(ElementTree.SubElement(request, "CONSTCOMP", id=self._id("cc"), bl=str(part[2]),
                                                   v=str(part[1])), "Constant")
            elif part[0] == "static":
                component = ElementTree.SubElement(request, "STATICCOMP", id=self._id("sc"), bl=str(part[2]))
                self._named(component, part[1])
                statics[part[1]] = component.get("id")
            else:
                ElementTree.SubElement(request, "SIMPLEPROXYCOMP", id=self._id("pc"), dest="data")
        ElementTree.SubElement(element, "POS")
        return element.get("id"), statics

    def template(self, qual, statics, services):
        """A DCLTMPL: statics {key: [STATICCOMP ids]} as SHSTATICs, services [(qual, PROTOCOLSERVICE id)].
        Returns ({key: SHSTATIC id}, {qual: DCLSRVTMPL id}, its id)."""
        element = ElementTree.SubElement(self.templates, "DCLTMPL", id=self._id("ct"))
        self._named(element, qual)
        shstatics = {}
        for key, component_ids in statics.items():
            static = ElementTree.SubElement(element, "SHSTATIC", id=self._id("sh"))
            self._named(static, key)
            for component in component_ids:
                ElementTree.SubElement(static, "STATICCOMPREF", idref=component)
            shstatics[key] = static.get("id")
        service_templates = {}
        for service_qual, protocol_id in services:
            service_template = ElementTree.SubElement(element, "DCLSRVTMPL", id=self._id("tt"), tmplref=protocol_id)
            self._named(service_template, service_qual)
            service_templates[service_qual] = service_template.get("id")
        return shstatics, service_templates, element.get("id")

    def instance(self, diag_class, qual, values, services, length=None):
        """A DIAGINST: values {SHSTATIC id: v}, services [(DCLSRVTMPL id, mayBeExec, trans or None)]."""
        element = ElementTree.SubElement(diag_class, "DIAGINST", id=self._id("di"))
        self._named(element, qual)
        for static, value in values.items():
            ElementTree.SubElement(element, "STATICVALUE", shstaticref=static, v=str(value))
        if length:
            container = ElementTree.SubElement(element, "SIMPLECOMPCONT")
            data = ElementTree.SubElement(container, "DATAOBJ", id=self._id("do"), dtref=self.datatype(length))
            ElementTree.SubElement(data, "QUAL").text = "Data"
        for template, allowed, trans in services:
            attributes = {"id": self._id("sv"), "tmplref": template, "mayBeExec": allowed}
            if trans:
                attributes["trans"] = trans
            ElementTree.SubElement(element, "SERVICE", attributes)

    def diag_class(self, template_id, qual):
        element = ElementTree.SubElement(self.variant, "DIAGCLASS", id=self._id("dc"), tmplref=template_id)
        self._named(element, qual)
        return element

    def write(self):
        d = self.d
        self.write_states()
        session_states = [self.states[("session", s)] for s in sorted(d.sessions)]
        locked = self.states[("security", 0)]
        unlocked = [self.states[("security", level)] for level in sorted(d.security_levels)]
        for sid, service in sorted(d.services.items()):
            if sid in (0x22, 0x2E, 0x31, 0x27):
                continue
            if sid == 0x10 or service.sub_functions:
                protocol, statics = self.protocol(service.name, [("const", sid, 8), ("static", "Sub", 8)] +
                                                  ([("data",)] if sid in (0x19, 0x28, 0x86) else []))
                shstatics, templates, template_id = self.template(service.name, {"Sub": [statics["Sub"]]},
                                                                  [("Request", protocol)])
                diag_class = self.diag_class(template_id, service.name)
                subs = sorted(d.sessions) if sid == 0x10 else sorted(service.sub_functions)
                for sub in subs:
                    trans = None
                    access = service.sub_functions.get(sub, service.access)
                    if sid == 0x10:
                        target = self.states[("session", sub)]
                        sources = d.sessions[sub].entered_from or set(d.sessions)
                        pairs = [(self.states[("session", s)], target) for s in sorted(sources)]
                        pairs += [(state, locked) for state in unlocked]       # a new session locks again
                        trans = "(" + ",".join(f"{a},{b}" for a, b in pairs) + ")"
                        access = service.access
                    self.instance(diag_class, f"{service.name}_{sub:02X}", {shstatics["Sub"]: sub},
                                  [(templates["Request"], self.may_be_exec(access), trans)])
            else:
                protocol, _statics = self.protocol(service.name, [("const", sid, 8), ("data",)])
                _shstatics, templates, template_id = self.template(service.name, {}, [("Request", protocol)])
                self.instance(self.diag_class(template_id, service.name), service.name, {},
                              [(templates["Request"], self.may_be_exec(service.access), None)])
        # SecurityAccess: requestSeed and sendKey of each level; sendKey unlocks.
        if 0x27 in d.services:
            seed, seed_statics = self.protocol("RequestSeed", [("const", 0x27, 8), ("static", "Seed", 8)])
            key, key_statics = self.protocol("SendKey", [("const", 0x27, 8), ("static", "Key", 8), ("data",)])
            shstatics, templates, template_id = self.template(
                "SecurityAccess", {"Seed": [seed_statics["Seed"]], "Key": [key_statics["Key"]]},
                [("RequestSeed", seed), ("SendKey", key)])
            diag_class = self.diag_class(template_id, "SecurityAccess")
            service = d.services[0x27]
            for level in sorted(d.security_levels):
                access = service.sub_functions.get(level, service.access)
                target = self.states[("security", level)]
                trans = "(" + ",".join(f"{state},{target}" for state in [locked] + unlocked) + ")"
                self.instance(diag_class, f"Level{level}", {shstatics["Seed"]: level, shstatics["Key"]: level + 1},
                              [(templates["RequestSeed"], self.may_be_exec(access), None),
                               (templates["SendKey"], self.may_be_exec(access), trans)])
        # Data identifiers: one instance each, read and (where writable) write.
        read, read_statics = self.protocol("ReadDataByIdentifier", [("const", 0x22, 8), ("static", "DID", 16)])
        write, write_statics = self.protocol("WriteDataByIdentifier",
                                             [("const", 0x2E, 8), ("static", "DID", 16), ("data",)])
        shstatics, templates, template_id = self.template(
            "DataIdentifier", {"DID": [read_statics["DID"], write_statics["DID"]]},
            [("Read", read), ("Write", write)])
        diag_class = self.diag_class(template_id, "DataIdentifiers")
        for did, entry in sorted(d.dids.items()):
            services = []
            if entry.read is not None:
                services.append((templates["Read"], self.may_be_exec(entry.read), None))
            if entry.write is not None:
                services.append((templates["Write"], self.may_be_exec(entry.write), None))
            self.instance(diag_class, entry.name.replace(" ", "_"), {shstatics["DID"]: did}, services, entry.length)
        # Routines: startRoutine, stopRoutine and requestRoutineResults, where each routine has them.
        if d.routines:
            controls = {0x01: "Start", 0x02: "Stop", 0x03: "Results"}
            protocols, rid_statics = [], []
            for sub, qual in controls.items():
                protocol, statics = self.protocol(f"{qual}Routine", [("const", 0x31, 8), ("const", sub, 8),
                                                                    ("static", "RID", 16), ("data",)])
                protocols.append((qual, protocol))
                rid_statics.append(statics["RID"])
            shstatics, templates, template_id = self.template("Routine", {"RID": rid_statics}, protocols)
            diag_class = self.diag_class(template_id, "Routines")
            for rid, routine in sorted(d.routines.items()):
                self.instance(diag_class, routine.name, {shstatics["RID"]: rid},
                              [(templates[controls[sub]], self.may_be_exec(access), None)
                               for sub, access in sorted(routine.sub_functions.items())])
        del session_states
        ElementTree.indent(self.root)
        return ElementTree.tostring(self.root, encoding="unicode", xml_declaration=True)


def main():
    text = Writer(dummy_description(EcuConfig())).write()
    TARGET.write_text(text + "\n", encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
