"""Write ODX/dummy_ecu.cdd: the Dummy ECU's diagnostics as a CANdela document, for TestExpert.

    python tools/make_dummy_cdd.py

It follows the structure CANdelaStudio writes - protocol services (REQ and POS with CONSTCOMP, STATICCOMP and
SIMPLEPROXYCOMP), class templates (DCLTMPL with SHSTATIC, SHPROXY and DCLSRVTMPL), the variant's DIAGCLASS /
DIAGINST / SERVICE with its data containers (SIMPLECOMPCONT: the data, and the response codes' texts), data
types (IDENT, TEXTTBL, LINCOMP with f, o, div and a UNIT), and state groups with mayBeExec and trans - but it is
generated here from the Dummy ECU's description, not exported by CANdelaStudio.
"""
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from canexpert.simulator.ecu import EcuConfig  # noqa: E402
from canexpert.test_expert.dummy import dummy_description  # noqa: E402

TARGET = ROOT / "ODX" / "dummy_ecu.cdd"
MAX_TEXT = 32                       # the longest text of a variable length


class Writer:
    def __init__(self, description):
        self.d = description
        self.root = ElementTree.Element("CANDELA", dtdvers="9.0.102")
        self.doc = ElementTree.SubElement(self.root, "ECUDOC", manufacturer="CAN Expert", doctype="inst")
        comment = ElementTree.SubElement(self.doc, "DESC")
        ElementTree.SubElement(comment, "TUV").text = ("The Dummy ECU of CAN Expert, generated by tools/make_dummy_cdd.py "
                                                       "in CANdelaStudio's structure (not exported by CANdelaStudio).")
        ElementTree.SubElement(self.doc, "PROTOCOLSTANDARD").text = "UDS"
        self.datatypes = ElementTree.SubElement(self.doc, "DATATYPES")
        self.groups = ElementTree.SubElement(self.doc, "STATEGROUPS")
        self.protocols = ElementTree.SubElement(self.doc, "PROTOCOLSERVICES")
        self.templates = ElementTree.SubElement(self.doc, "DCLTMPLS")
        ecu = ElementTree.SubElement(self.doc, "ECU", id="ecu")
        self._named(ecu, "DummyECU", "Dummy ECU")
        self.variant = ElementTree.SubElement(ecu, "VAR", id="var_common")
        self._named(self.variant, "CommonDiagnostics", "Common diagnostics")
        self.ids = 0
        self.lengths = {}
        self.shproxies = {}              # DCLTMPL id -> {dest: SHPROXY id}
        self.states = {}                 # ("session", id) / ("security", level or 0) -> 1-based index

    def _id(self, prefix):
        self.ids += 1
        return f"_{prefix}{self.ids:04d}"

    @staticmethod
    def _named(element, qual, name=None):
        name_element = ElementTree.SubElement(element, "NAME")
        ElementTree.SubElement(name_element, "TUV", {"xml:lang": "en-US"}).text = name or qual
        ElementTree.SubElement(element, "QUAL").text = qual
        return element

    def datatype(self, length):
        """A byte field of length bytes, for a DID's data."""
        if length not in self.lengths:
            element = ElementTree.SubElement(self.datatypes, "IDENT", id=self._id("dt"))
            self._named(element, f"Bytes{length}")
            ElementTree.SubElement(element, "CVALUETYPE", bl="8", bo="21", enc="uns", sz="no", qty="field",
                                   minsz=str(length), maxsz=str(length))
            ElementTree.SubElement(element, "PVALUETYPE", bl="8", bo="21", enc="uns", sz="no")
            self.lengths[length] = element.get("id")
        return self.lengths[length]

    def field_type(self, field):
        """The data type of a DID's field: a text table (TEXTTBL with TEXTMAPs), a linear type with its valid
        ranges (LINCOMP with COMPs), text (IDENT of ASCII characters) or a plain number."""
        encoding = {"signed": "sgn", "ascii": "asc", "bcd": "bcd"}.get(field.encoding, "uns")
        if field.texts:
            element = ElementTree.SubElement(self.datatypes, "TEXTTBL", id=self._id("dt"))
            self._named(element, f"{field.name}Table")
            ElementTree.SubElement(element, "CVALUETYPE", bl=str(field.bits), bo="21", enc=encoding, sz="no",
                                   qty="atom")
            ElementTree.SubElement(element, "PVALUETYPE", bl="0", bo="21", enc="asc", sz="yes", qty="field")
            for value, text in sorted(field.texts.items()):
                textmap = ElementTree.SubElement(element, "TEXTMAP", s=str(value), e=str(value))
                ElementTree.SubElement(ElementTree.SubElement(textmap, "TEXT"), "TUV", {"xml:lang": "en-US"}).text = text
        elif field.numeric and (field.valid or field.unit or (field.scale, field.shift) != (1.0, 0.0)):
            element = ElementTree.SubElement(self.datatypes, "LINCOMP", id=self._id("dt"))
            self._named(element, field.name)
            ElementTree.SubElement(element, "CVALUETYPE", bl=str(field.bits), bo="21", enc=encoding, sig="0", df="hex",
                                   sz="no", qty="atom")
            physical = ElementTree.SubElement(element, "PVALUETYPE", bl="64", bo="21", enc="dbl", sig="2", df="flt",
                                              sz="no", qty="atom")
            if field.unit:
                ElementTree.SubElement(physical, "UNIT").text = field.unit
            divisor = 100 if (field.scale * 100) % 1 == 0 and field.scale % 1 else 1   # 0.01 is 1 / 100
            factor, offset = field.scale * divisor, field.shift * divisor
            for low, top in field.valid or [(None, None)]:
                limits = {"s": str(low), "e": str(top)} if low is not None else {}
                ElementTree.SubElement(element, "COMP", f=f"{factor:g}", o=f"{offset:g}", div=str(divisor), **limits)
        elif not field.numeric:
            element = ElementTree.SubElement(self.datatypes, "IDENT", id=self._id("dt"))
            self._named(element, f"{field.name}{field.bits // 8 or 'Any'}")
            sizes = (1, MAX_TEXT) if field.variable else (field.bits // 8, field.bits // 8)
            ElementTree.SubElement(element, "CVALUETYPE", bl="8", bo="21", enc=encoding, sz="no", qty="field",
                                   minsz=str(sizes[0]), maxsz=str(sizes[1]))
            ElementTree.SubElement(element, "PVALUETYPE", bl="8", bo="21", enc=encoding, sz="no")
        else:
            element = ElementTree.SubElement(self.datatypes, "IDENT", id=self._id("dt"))
            self._named(element, field.name)
            ElementTree.SubElement(element, "CVALUETYPE", bl=str(field.bits), bo="21", enc=encoding, sz="no",
                                   qty="atom")
            ElementTree.SubElement(element, "PVALUETYPE", bl=str(field.bits), bo="21", enc=encoding, sz="no")
        return element.get("id")

    def write_states(self):
        sessions = ElementTree.SubElement(self.groups, "STATEGROUP", id=self._id("sg"), spec="session")
        self._named(sessions, "Session")
        for session in sorted(self.d.sessions.values(), key=lambda s: s.id):
            self._named(ElementTree.SubElement(sessions, "STATE", id=self._id("st")), session.name.replace(" ", ""),
                        session.name)
            self.states[("session", session.id)] = len(self.states) + 1
        security = ElementTree.SubElement(self.groups, "STATEGROUP", id=self._id("sg"), spec="security")
        self._named(security, "SecurityAccess")
        self._named(ElementTree.SubElement(security, "STATE", id=self._id("st")), "Locked")
        self.states[("security", 0)] = len(self.states) + 1
        for level in sorted(self.d.security_levels):
            self._named(ElementTree.SubElement(security, "STATE", id=self._id("st")), f"UnlockedLevel{level}")
            self.states[("security", level)] = len(self.states) + 1

    def may_be_exec(self, access) -> str:
        sessions = access.sessions or set(self.d.sessions)
        levels = access.levels or {0, *self.d.security_levels}
        indexes = sorted([self.states[("session", s)] for s in sessions] + [self.states[("security", l)] for l in levels])
        return "(" + ",".join(str(index) for index in indexes) + ")"

    def protocol(self, qual, parts, answer=()):
        """A PROTOCOLSERVICE: parts of its request (REQ) and of its positive answer (POS) are ("const", value,
        bits), ("static", key, bits) or ("data",). Returns (its id, {key: STATICCOMP ids}, [SIMPLEPROXYCOMP
        ids]); a static of the request and one of the answer with the same key share the key."""
        element = ElementTree.SubElement(self.protocols, "PROTOCOLSERVICE", id=self._id("ps"), func="1", phys="1")
        self._named(element, qual)
        statics, proxies = {}, []
        for tag, components in (("REQ", parts), ("POS", answer)):
            message = ElementTree.SubElement(element, tag)
            for part in components:
                if part[0] == "const":
                    self._named(ElementTree.SubElement(message, "CONSTCOMP", id=self._id("cc"), bl=str(part[2]),
                                                       v=str(part[1])), "Constant")
                elif part[0] == "static":
                    component = ElementTree.SubElement(message, "STATICCOMP", id=self._id("sc"), bl=str(part[2]))
                    self._named(component, part[1])
                    statics.setdefault(part[1], []).append(component.get("id"))
                else:
                    proxy = ElementTree.SubElement(message, "SIMPLEPROXYCOMP", id=self._id("pc"), dest="data")
                    self._named(proxy, "Data")
                    proxies.append(proxy.get("id"))
        return element.get("id"), {key: ids[0] for key, ids in statics.items()}, proxies, statics

    def template(self, qual, statics, services, proxies=None):
        """A DCLTMPL: statics {key: [STATICCOMP ids]} as SHSTATICs, services [(qual, PROTOCOLSERVICE id)],
        proxies {dest: [SIMPLEPROXYCOMP ids]} as SHPROXYs. Returns ({key: SHSTATIC id}, {qual: DCLSRVTMPL id},
        its id), and keeps the SHPROXY ids in self.shproxies[its id]."""
        element = ElementTree.SubElement(self.templates, "DCLTMPL", id=self._id("ct"))
        self._named(element, qual)
        shstatics = {}
        for key, component_ids in statics.items():
            static = ElementTree.SubElement(element, "SHSTATIC", id=self._id("sh"))
            self._named(static, key)
            for component in component_ids:
                ElementTree.SubElement(static, "STATICCOMPREF", idref=component)
            shstatics[key] = static.get("id")
        self.shproxies[element.get("id")] = {}
        for dest, component_ids in (proxies or {}).items():
            shproxy = ElementTree.SubElement(element, "SHPROXY", id=self._id("sp"), dest=dest)
            self._named(shproxy, "DATA" if dest == "data" else "RC")
            for component in component_ids:
                ElementTree.SubElement(shproxy, "PROXYCOMPREF", idref=component)
            self.shproxies[element.get("id")][dest] = shproxy.get("id")
        service_templates = {}
        for service_qual, protocol_id in services:
            service_template = ElementTree.SubElement(element, "DCLSRVTMPL", id=self._id("tt"), tmplref=protocol_id)
            self._named(service_template, service_qual)
            service_templates[service_qual] = service_template.get("id")
        return shstatics, service_templates, element.get("id")

    def instance(self, diag_class, qual, values, services, length=None, fields=(), shproxies=None):
        """A DIAGINST: values {SHSTATIC id: v}, services [(DCLSRVTMPL id, mayBeExec, trans or None)]; a DID's
        data as its fields' DATAOBJs, or one byte field of length bytes, in the data container of the class's
        SHPROXY "data", beside a container of its response codes' texts (SHPROXY "resCode") as CANdelaStudio
        writes them."""
        element = ElementTree.SubElement(diag_class, "DIAGINST", id=self._id("di"))
        self._named(element, qual)
        for static, value in values.items():
            ElementTree.SubElement(element, "STATICVALUE", shstaticref=static, v=str(value))
        shproxies = shproxies or {}
        if "resCode" in shproxies:
            codes = ElementTree.SubElement(element, "SIMPLECOMPCONT", shproxyref=shproxies["resCode"])
            special = ElementTree.SubElement(codes, "SPECDATAOBJ", id=self._id("do"), spec="rc")
            ElementTree.SubElement(special, "QUAL").text = "NRC"
            table = ElementTree.SubElement(special, "TEXTTBL", id=self._id("dt"))
            ElementTree.SubElement(table, "QUAL").text = "LocalTable"
            ElementTree.SubElement(table, "CVALUETYPE", bl="8", bo="21", enc="uns", sz="no", qty="atom")
            for nrc, text in ((0x13, "Incorrect message length or invalid format"), (0x31, "Request out of range")):
                mapping = ElementTree.SubElement(table, "TEXTMAP", s=str(nrc), e=str(nrc))
                ElementTree.SubElement(ElementTree.SubElement(mapping, "TEXT"), "TUV", {"xml:lang": "en-US"}).text = text
        attributes = {"shproxyref": shproxies["data"]} if "data" in shproxies else {}
        if fields:
            container = ElementTree.SubElement(element, "SIMPLECOMPCONT", attributes)
            for field in fields:
                data = ElementTree.SubElement(container, "DATAOBJ", id=self._id("do"), spec="no",
                                              dtref=self.field_type(field))
                ElementTree.SubElement(data, "QUAL").text = field.name
        elif length:
            container = ElementTree.SubElement(element, "SIMPLECOMPCONT", attributes)
            data = ElementTree.SubElement(container, "DATAOBJ", id=self._id("do"), spec="no",
                                          dtref=self.datatype(length))
            ElementTree.SubElement(data, "QUAL").text = "Data"
        for template, allowed, trans in services:
            attributes = {"id": self._id("sv"), "tmplref": template, "mayBeExec": allowed}
            if trans:
                attributes["trans"] = trans
            ElementTree.SubElement(element, "SERVICE", attributes)

    def diag_class(self, template_id, qual):
        element = ElementTree.SubElement(self.variant, "DIAGCLASS", id=self._id("dc"), tmplref=template_id)
        self._named(element, qual)
        return element

    def write(self):
        d = self.d
        self.write_states()
        session_states = [self.states[("session", s)] for s in sorted(d.sessions)]
        locked = self.states[("security", 0)]
        unlocked = [self.states[("security", level)] for level in sorted(d.security_levels)]
        io_dids = any(entry.io is not None for entry in d.dids.values())
        for sid, service in sorted(d.services.items()):
            if sid in (0x22, 0x2E, 0x31, 0x27) or (sid == 0x2F and io_dids):
                continue
            if sid == 0x10 or service.sub_functions:
                protocol, statics, _proxies, _all = self.protocol(
                    service.name, [("const", sid, 8), ("static", "Sub", 8)] + ([("data",)] if sid in (0x19, 0x28, 0x86)
                                                                              else []))
                shstatics, templates, template_id = self.template(service.name, {"Sub": [statics["Sub"]]},
                                                                  [("Request", protocol)])
                diag_class = self.diag_class(template_id, service.name)
                subs = sorted(d.sessions) if sid == 0x10 else sorted(service.sub_functions)
                for sub in subs:
                    trans = None
                    access = service.sub_functions.get(sub, service.access)
                    if sid == 0x10:
                        target = self.states[("session", sub)]
                        sources = d.sessions[sub].entered_from or set(d.sessions)
                        pairs = [(self.states[("session", s)], target) for s in sorted(sources)]
                        pairs += [(state, locked) for state in unlocked]       # a new session locks again
                        trans = "(" + ",".join(f"{a},{b}" for a, b in pairs) + ")"
                        access = service.access
                    self.instance(diag_class, f"{service.name}_{sub:02X}", {shstatics["Sub"]: sub},
                                  [(templates["Request"], self.may_be_exec(access), trans)])
            else:
                protocol, _statics, _proxies, _all = self.protocol(service.name, [("const", sid, 8), ("data",)])
                _shstatics, templates, template_id = self.template(service.name, {}, [("Request", protocol)])
                self.instance(self.diag_class(template_id, service.name), service.name, {},
                              [(templates["Request"], self.may_be_exec(service.access), None)])
        # SecurityAccess: requestSeed and sendKey of each level; sendKey unlocks.
        if 0x27 in d.services:
            seed, seed_statics, _proxies, _all = self.protocol("RequestSeed", [("const", 0x27, 8), ("static", "Seed", 8)])
            key, key_statics, _proxies, _all = self.protocol("SendKey", [("const", 0x27, 8), ("static", "Key", 8),
                                                                        ("data",)])
            shstatics, templates, template_id = self.template(
                "SecurityAccess", {"Seed": [seed_statics["Seed"]], "Key": [key_statics["Key"]]},
                [("RequestSeed", seed), ("SendKey", key)])
            diag_class = self.diag_class(template_id, "SecurityAccess")
            service = d.services[0x27]
            for level in sorted(d.security_levels):
                access = service.sub_functions.get(level, service.access)
                target = self.states[("security", level)]
                trans = "(" + ",".join(f"{state},{target}" for state in [locked] + unlocked) + ")"
                self.instance(diag_class, f"Level{level}", {shstatics["Seed"]: level, shstatics["Key"]: level + 1},
                              [(templates["RequestSeed"], self.may_be_exec(access), None),
                               (templates["SendKey"], self.may_be_exec(access), trans)])
        # Data identifiers: one instance each, read and (where writable) write.
        read, _statics, read_proxies, read_statics = self.protocol(
            "ReadDataByIdentifier", [("const", 0x22, 8), ("static", "DID", 16)],
            [("const", 0x62, 8), ("static", "DID", 16), ("data",)])
        write, _statics, write_proxies, write_statics = self.protocol(
            "WriteDataByIdentifier", [("const", 0x2E, 8), ("static", "DID", 16), ("data",)],
            [("const", 0x6E, 8), ("static", "DID", 16)])
        io, _statics, io_proxies, io_statics = self.protocol(
            "InputOutputControlByIdentifier", [("const", 0x2F, 8), ("static", "DID", 16), ("data",)],
            [("const", 0x6F, 8), ("static", "DID", 16), ("data",)])
        shstatics, templates, template_id = self.template(
            "DataIdentifier", {"DID": read_statics["DID"] + write_statics["DID"] + io_statics["DID"]},
            [("Read", read), ("Write", write), ("IOControl", io)],
            {"data": read_proxies + write_proxies + io_proxies, "resCode": []})
        diag_class = self.diag_class(template_id, "DataIdentifiers")
        for did, entry in sorted(d.dids.items()):
            services = []
            if entry.read is not None:
                services.append((templates["Read"], self.may_be_exec(entry.read), None))
            if entry.write is not None:
                services.append((templates["Write"], self.may_be_exec(entry.write), None))
            if entry.io is not None:
                services.append((templates["IOControl"], self.may_be_exec(entry.io), None))
            self.instance(diag_class, entry.name.replace(" ", "_"), {shstatics["DID"]: did}, services, entry.length,
                          entry.fields, self.shproxies[template_id])
        # Routines: startRoutine, stopRoutine and requestRoutineResults, where each routine has them.
        if d.routines:
            controls = {0x01: "Start", 0x02: "Stop", 0x03: "Results"}
            protocols, rid_statics = [], []
            for sub, qual in controls.items():
                protocol, statics, _proxies, _all = self.protocol(f"{qual}Routine", [("const", 0x31, 8),
                                                                                  ("const", sub, 8),
                                                                                  ("static", "RID", 16), ("data",)])
                protocols.append((qual, protocol))
                rid_statics.append(statics["RID"])
            shstatics, templates, template_id = self.template("Routine", {"RID": rid_statics}, protocols)
            diag_class = self.diag_class(template_id, "Routines")
            for rid, routine in sorted(d.routines.items()):
                self.instance(diag_class, routine.name, {shstatics["RID"]: rid},
                              [(templates[controls[sub]], self.may_be_exec(access), None)
                               for sub, access in sorted(routine.sub_functions.items())])
        del session_states
        ElementTree.indent(self.root)
        return ElementTree.tostring(self.root, encoding="unicode", xml_declaration=True)


def main():
    text = Writer(dummy_description(EcuConfig())).write()
    TARGET.write_text(text + "\n", encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
