"""Write ODX/dummy_ecu_services.odx-d: the Dummy ECU's diagnostics as an ODX 2.2 diagnostic layer container.

    python tools/make_dummy_odx.py

A base variant with the Dummy ECU's services - their requests' coded constants, their pre-condition states and
the state transitions they cause in a SESSION and a SECURITY state chart -, its DIDs' data (DATA-OBJECT-PROPs:
text tables, linear scales, limits, units, ASCII) in their positive responses, and two ECU variants told apart
by their ECU-VARIANT-PATTERNs: Application (F195 answers APP-1.0.0) and Bootloader (BOOTLOADER), which does
not have the application's services and data. It is generated here from the Dummy ECU's description; odxtools
reads it as it reads any ODX file.
"""
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from canexpert.simulator.ecu import BOOT_SERVICES, BOOT_VERSION, EcuConfig  # noqa: E402
from canexpert.test_expert.dummy import dummy_description  # noqa: E402

TARGET = ROOT / "ODX" / "dummy_ecu_services.odx-d"
XSI = "http://www.w3.org/2001/XMLSchema-instance"
TYPE = f"{{{XSI}}}type"
APPLICATION_VERSION = "APP-1.0.0"
ROUTINE_CONTROLS = {0x01: "Start", 0x02: "Stop", 0x03: "RequestResults"}


def _element(parent, tag, text=None, **attributes):
    element = ElementTree.SubElement(parent, tag, {key.replace("__", "-"): str(value)
                                                   for key, value in attributes.items()})
    if text is not None:
        element.text = str(text)
    return element


class Writer:
    def __init__(self, description):
        self.d = description
        ElementTree.register_namespace("xsi", XSI)
        self.root = ElementTree.Element("ODX", {"MODEL-VERSION": "2.2.0"})
        comment = ElementTree.Comment(" The Dummy ECU of CAN Expert, generated by tools/make_dummy_odx.py for TestExpert ")
        self.root.append(comment)
        container = _element(self.root, "DIAG-LAYER-CONTAINER", ID="DLC.DummyECU_Services")
        _element(container, "SHORT-NAME", "DummyECU_Services")
        _element(container, "LONG-NAME", "CAN Expert Dummy ECU: its services")
        base_variants = _element(container, "BASE-VARIANTS")
        self.base = _element(base_variants, "BASE-VARIANT", ID="BV.DummyECU")
        _element(self.base, "SHORT-NAME", "DummyECU")
        _element(self.base, "LONG-NAME", "CAN Expert Dummy ECU")
        spec = _element(self.base, "DIAG-DATA-DICTIONARY-SPEC")
        self.dops = _element(spec, "DATA-OBJECT-PROPS")
        self.units = _element(_element(spec, "UNIT-SPEC"), "UNITS")
        self.comms = _element(self.base, "DIAG-COMMS")
        self.requests = _element(self.base, "REQUESTS")
        self.responses = _element(self.base, "POS-RESPONSES")
        self.charts = _element(self.base, "STATE-CHARTS")
        self.ecu_variants = _element(container, "ECU-VARIANTS")
        self.names = set()
        self.dop_ids = {}
        self.unit_ids = {}
        self.states = {}                  # ("session", id) / ("security", level or 0) -> STATE ID
        self.transitions = {}             # (from key, to key) -> STATE-TRANSITION ID
        self.application_only = []        # the services the bootloader does not have

    def _unique(self, name):
        base, number = name, 1
        while name in self.names:
            number += 1
            name = f"{base}_{number}"
        self.names.add(name)
        return name

    # --- data ---------------------------------------------------------------------------------------------

    def unit(self, name):
        if name not in self.unit_ids:
            unit = _element(self.units, "UNIT", ID=f"U.{len(self.unit_ids)}")
            _element(unit, "SHORT-NAME", f"unit_{len(self.unit_ids)}")
            _element(unit, "DISPLAY-NAME", name)
            self.unit_ids[name] = unit.get("ID")
        return self.unit_ids[name]

    def dop(self, field):
        """The DATA-OBJECT-PROP of a DID's field: a text table, a linear scale, limits and a unit, or text."""
        key = (field.bits, field.encoding, tuple(field.valid), tuple(sorted(field.texts.items())), field.scale,
               field.shift, field.unit)
        if key in self.dop_ids:
            return self.dop_ids[key]
        dop = _element(self.dops, "DATA-OBJECT-PROP", ID=f"DOP.{len(self.dop_ids)}")
        _element(dop, "SHORT-NAME", self._unique(f"{field.name}_{field.bits}"))
        compu = _element(dop, "COMPU-METHOD")
        if field.texts:
            _element(compu, "CATEGORY", "TEXTTABLE")
            scales = _element(_element(compu, "COMPU-INTERNAL-TO-PHYS"), "COMPU-SCALES")
            for value, text in sorted(field.texts.items()):
                scale = _element(scales, "COMPU-SCALE")
                _element(scale, "LOWER-LIMIT", value)
                _element(scale, "UPPER-LIMIT", value)
                _element(_element(scale, "COMPU-CONST"), "VT", text)
        elif field.numeric and (field.scale, field.shift) != (1.0, 0.0):
            _element(compu, "CATEGORY", "LINEAR")
            scale = _element(_element(_element(compu, "COMPU-INTERNAL-TO-PHYS"), "COMPU-SCALES"), "COMPU-SCALE")
            coefficients = _element(scale, "COMPU-RATIONAL-COEFFS")
            numerator = _element(coefficients, "COMPU-NUMERATOR")
            _element(numerator, "V", f"{field.shift:g}")
            _element(numerator, "V", f"{field.scale:g}")
            _element(_element(coefficients, "COMPU-DENOMINATOR"), "V", "1")
        else:
            _element(compu, "CATEGORY", "IDENTICAL")
        text = field.encoding == "ascii"
        _element(dop, "DIAG-CODED-TYPE", BASE__DATA__TYPE="A_ASCIISTRING" if text else "A_UINT32",
                 **{TYPE: "STANDARD-LENGTH-TYPE"}).append(_leaf("BIT-LENGTH", field.bits))
        physical = "A_UNICODE2STRING" if text or field.texts else \
            "A_FLOAT64" if (field.scale, field.shift) != (1.0, 0.0) else "A_UINT32"
        _element(dop, "PHYSICAL-TYPE", BASE__DATA__TYPE=physical)
        if field.valid and not field.texts:
            constraint = _element(dop, "INTERNAL-CONSTR")
            low, high = field.valid[0]
            _element(constraint, "LOWER-LIMIT", low, INTERVAL__TYPE="CLOSED")
            _element(constraint, "UPPER-LIMIT", high, INTERVAL__TYPE="CLOSED")
        if field.unit:
            _element(dop, "UNIT-REF", ID__REF=self.unit(field.unit))
        self.dop_ids[key] = dop.get("ID")
        return dop.get("ID")

    # --- states -------------------------------------------------------------------------------------------

    def write_states(self):
        d = self.d
        session = _element(self.charts, "STATE-CHART", ID="SC.Session")
        _element(session, "SHORT-NAME", "Session")
        _element(session, "SEMANTIC", "SESSION")
        transitions = _element(session, "STATE-TRANSITIONS")
        names = {s.id: s.name.replace(" ", "") for s in d.sessions.values()}
        for target in sorted(d.sessions):
            for source in sorted(d.sessions[target].entered_from or d.sessions):
                self._transition(transitions, ("session", source), names[source], ("session", target), names[target])
        _element(session, "START-STATE-SNREF", SHORT__NAME=names[min(d.sessions)])
        states = _element(session, "STATES")
        for sid in sorted(d.sessions):
            state = _element(states, "STATE", ID=f"S.{names[sid]}")
            _element(state, "SHORT-NAME", names[sid])
            _element(state, "LONG-NAME", d.sessions[sid].name)
            self.states[("session", sid)] = state.get("ID")
        security = _element(self.charts, "STATE-CHART", ID="SC.Security")
        _element(security, "SHORT-NAME", "SecurityAccess")
        _element(security, "SEMANTIC", "SECURITY")
        transitions = _element(security, "STATE-TRANSITIONS")
        for level in sorted(d.security_levels):
            self._transition(transitions, ("security", 0), "Locked", ("security", level), f"UnlockedLevel{level}")
            self._transition(transitions, ("security", level), f"UnlockedLevel{level}", ("security", 0), "Locked")
        _element(security, "START-STATE-SNREF", SHORT__NAME="Locked")
        states = _element(security, "STATES")
        for level, name in [(0, "Locked")] + [(level, f"UnlockedLevel{level}") for level in sorted(d.security_levels)]:
            state = _element(states, "STATE", ID=f"S.{name}")
            _element(state, "SHORT-NAME", name)
            self.states[("security", level)] = state.get("ID")

    def _transition(self, parent, source, source_name, target, target_name):
        transition = _element(parent, "STATE-TRANSITION", ID=f"ST.{source_name}_{target_name}")
        _element(transition, "SHORT-NAME", f"{source_name}_{target_name}")
        _element(transition, "SOURCE-SNREF", SHORT__NAME=source_name)
        _element(transition, "TARGET-SNREF", SHORT__NAME=target_name)
        self.transitions[(source, target)] = transition.get("ID")

    def allowed(self, access):
        """The pre-condition states of an Access: its sessions (all when none) and its levels' unlocked states
        (locked or not when none) - nothing when it allows everything."""
        if not access.sessions and not access.levels:
            return []
        sessions = access.sessions or set(self.d.sessions)
        levels = access.levels or {0, *self.d.security_levels}
        return [self.states[("session", s)] for s in sorted(sessions)] + \
            [self.states[("security", level)] for level in sorted(levels)]

    # --- services -------------------------------------------------------------------------------------------

    def service(self, name, constants, access, transitions=(), values=(), response=None, application_only=False):
        """A DIAG-SERVICE: constants [(value, bits)] of its request, values [(name, dop id, bits)] after them, its
        pre-condition states and state transitions; response: the VALUE parameters of its positive response
        [(name, dop id, byte position)] (a DID's data), after its SID and the request's bytes it repeats."""
        name = self._unique(name)
        comm = _element(self.comms, "DIAG-SERVICE", ID=f"DS.{name}")
        _element(comm, "SHORT-NAME", name)
        states = self.allowed(access)
        if states:
            refs = _element(comm, "PRE-CONDITION-STATE-REFS")
            for state in states:
                _element(refs, "PRE-CONDITION-STATE-REF", ID__REF=state)
        if transitions:
            refs = _element(comm, "STATE-TRANSITION-REFS")
            for transition in transitions:
                _element(refs, "STATE-TRANSITION-REF", ID__REF=transition)
        _element(comm, "REQUEST-REF", ID__REF=f"RQ.{name}")
        _element(_element(comm, "POS-RESPONSE-REFS"), "POS-RESPONSE-REF", ID__REF=f"PR.{name}")
        request = _element(self.requests, "REQUEST", ID=f"RQ.{name}")
        _element(request, "SHORT-NAME", f"RQ_{name}")
        params = _element(request, "PARAMS")
        position = 0
        for index, (value, bits) in enumerate(constants):
            _coded_const(params, "SID_RQ" if index == 0 else f"Const{index}", position, value, bits,
                         "SERVICE-ID" if index == 0 else None)
            position += bits // 8
        for value_name, dop_id, bits in values:
            param = _element(params, "PARAM", SEMANTIC="DATA", **{TYPE: "VALUE"})
            _element(param, "SHORT-NAME", value_name)
            _element(param, "BYTE-POSITION", position)
            _element(param, "DOP-REF", ID__REF=dop_id)
            position += bits // 8
        answer = _element(self.responses, "POS-RESPONSE", ID=f"PR.{name}")
        _element(answer, "SHORT-NAME", f"PR_{name}")
        params = _element(answer, "PARAMS")
        _coded_const(params, "SID_PR", 0, (constants[0][0] + 0x40) & 0xFF, 8, "SERVICE-ID")
        echoed = sum(bits for _value, bits in constants[1:]) // 8
        if echoed:
            param = _element(params, "PARAM", **{TYPE: "MATCHING-REQUEST-PARAM"})
            _element(param, "SHORT-NAME", "Echo")
            _element(param, "BYTE-POSITION", 1)
            _element(param, "REQUEST-BYTE-POS", 1)
            _element(param, "BYTE-LENGTH", echoed)
        for value_name, dop_id, byte in response or ():
            param = _element(params, "PARAM", SEMANTIC="DATA", **{TYPE: "VALUE"})
            _element(param, "SHORT-NAME", value_name)
            _element(param, "BYTE-POSITION", byte)
            _element(param, "DOP-REF", ID__REF=dop_id)
        if application_only:
            self.application_only.append(name)
        return name

    def write(self):
        d = self.d
        self.write_states()
        unlocked = [("security", level) for level in sorted(d.security_levels)]
        boot = BOOT_SERVICES
        for sid, service in sorted(d.services.items()):
            if sid in (0x22, 0x2E, 0x31, 0x27):
                continue
            if sid == 0x10:
                for sub in sorted(d.sessions):
                    sources = d.sessions[sub].entered_from or set(d.sessions)
                    transitions = [self.transitions[(("session", source), ("session", sub))] for source in sorted(sources)]
                    transitions += [self.transitions[(state, ("security", 0))] for state in unlocked]
                    self.service(f"{d.session_name(sub).replace(' ', '')}_Start", [(0x10, 8), (sub, 8)],
                                 service.access, transitions)
            elif service.sub_functions:
                for sub, access in sorted(service.sub_functions.items()):
                    self.service(f"{service.name}_{sub:02X}", [(sid, 8), (sub, 8)], access,
                                 application_only=sid not in boot)
            else:
                self.service(service.name, [(sid, 8)], service.access, application_only=sid not in boot)
        if 0x27 in d.services:
            service = d.services[0x27]
            for level in sorted(d.security_levels):
                access = service.sub_functions.get(level, service.access)
                self.service(f"Level{level}_RequestSeed", [(0x27, 8), (level, 8)], access)
                key_dop = self.dop(_Field(f"Key{level}", 32))
                self.service(f"Level{level}_SendKey", [(0x27, 8), (level + 1, 8)], access,
                             [self.transitions[(("security", 0), ("security", level))]], [("Key", key_dop, 32)])
        for did, entry in sorted(d.dids.items()):
            name = entry.name.replace(" ", "_")
            response = [(item.name, self.dop(item), 3 + item.position // 8) for item in entry.fields]
            signal = any(item.scale != 1.0 for item in entry.fields)       # the application's measured data
            if entry.read is not None:
                self.service(f"{name}_Read", [(0x22, 8), (did, 16)], entry.read, response=response,
                             application_only=signal)
            if entry.write is not None:
                values = [(item.name, self.dop(item), item.bits) for item in entry.fields]
                self.service(f"{name}_Write", [(0x2E, 8), (did, 16)], entry.write, values=values)
        for rid, routine in sorted(d.routines.items()):
            for sub, access in sorted(routine.sub_functions.items()):
                self.service(f"{routine.name}_{ROUTINE_CONTROLS.get(sub, sub)}", [(0x31, 8), (sub, 8), (rid, 16)],
                             access, application_only=rid not in (0xFF00, 0xFF01))
        version = next((f"{entry.name.replace(' ', '_')}_Read" for did, entry in d.dids.items() if did == 0xF195), None)
        self.variant("Application", version, APPLICATION_VERSION, [])
        self.variant("Bootloader", version, BOOT_VERSION.decode(), self.application_only)
        ElementTree.indent(self.root)
        return ElementTree.tostring(self.root, encoding="unicode", xml_declaration=True)

    def variant(self, name, service, expected, not_inherited):
        variant = _element(self.ecu_variants, "ECU-VARIANT", ID=f"EV.{name}")
        _element(variant, "SHORT-NAME", name)
        patterns = _element(variant, "ECU-VARIANT-PATTERNS")
        parameter = _element(_element(_element(patterns, "ECU-VARIANT-PATTERN"), "MATCHING-PARAMETERS"),
                             "MATCHING-PARAMETER")
        _element(parameter, "EXPECTED-VALUE", expected)
        _element(parameter, "DIAG-COMM-SNREF", SHORT__NAME=service)
        _element(parameter, "OUT-PARAM-IF-SNREF", SHORT__NAME="Text")
        parent = _element(_element(variant, "PARENT-REFS"), "PARENT-REF", ID__REF="BV.DummyECU",
                          **{TYPE: "BASE-VARIANT-REF"})
        if not_inherited:
            comms = _element(parent, "NOT-INHERITED-DIAG-COMMS")
            for comm in not_inherited:
                _element(_element(comms, "NOT-INHERITED-DIAG-COMM"), "DIAG-COMM-SNREF", SHORT__NAME=comm)


class _Field:
    """A plain value of bits bits (a key)."""

    def __init__(self, name, bits):
        self.name, self.bits = name, bits
        self.encoding, self.valid, self.texts, self.scale, self.shift, self.unit = "bytes", [], {}, 1.0, 0.0, ""
        self.numeric = False


def _leaf(tag, text):
    element = ElementTree.Element(tag)
    element.text = str(text)
    return element


def _coded_const(params, name, position, value, bits, semantic=None):
    attributes = {TYPE: "CODED-CONST"}
    if semantic:
        attributes["SEMANTIC"] = semantic
    param = _element(params, "PARAM", **attributes)
    _element(param, "SHORT-NAME", name)
    _element(param, "BYTE-POSITION", position)
    _element(param, "CODED-VALUE", value)
    _element(param, "DIAG-CODED-TYPE", BASE__DATA__TYPE="A_UINT32",
             **{TYPE: "STANDARD-LENGTH-TYPE"}).append(_leaf("BIT-LENGTH", bits))


def main():
    text = Writer(dummy_description(EcuConfig())).write()
    TARGET.write_text(text + "\n", encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
